name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Biome rage
        run: biome rage
      - name: Run Biome
        run: biome ci . --verbose
